column_dtypes = {'nhpdpropertyid': "string",
                 'propertyname': "string",
                 'propertyaddress': "string",
                 'city': 'string',
                 'state': 'string',
                 'zip': 'string',
                 'cbsacode': "string",
                 'cbsatype': "string",
                 'county': "string",
                 'countycode': "int64",
                 'censustract': "string",
       'congressionaldistrict': 'string',
                 'latitude': 'float',
                 'longitude': 'float',
                 'propertystatus': 'string',
                 'activesubsidies': "int64",
                 'totalinconclusivesubsidies': "int64",
       'totalinactivesubsidies', 'totalunits', 'earlieststartdate',
       'earliestenddate', 'latestenddate', 'owner', 'ownertype', 'managername',
       'managertype', 'hudpropertyid', 'reacscore1', 'reacscore1date',
       'reacscore2', 'reacscore2date', 'reacscore3', 'reacscore3date',
       'studioonebedroomunits', 'twobedroomunits', 'threeplusbedroomunits',
       'percentofelihouseholds', 'targettenanttype', 'fairmarketrent_2br',
       'earliestconstructiondate', 'latestconstructiondate', 'occupancyrate',
       'averagemonthsoftenancy', 'numberactivesection8',
       'numberinconclusivesection8', 'numberinactivesection8', 's8_1_id',
       's8_1_status', 's8_1_programname', 's8_1_renewalstatus',
       's8_1_startdate', 's8_1_enddate', 's8_1_assistedunits',
       's8_1_renttofmr', 's8_1_inacstatusdesc', 's8_2_id', 's8_2_status',
       's8_2_programname', 's8_2_renewalstatus', 's8_2_startdate',
       's8_2_enddate', 's8_2_assistedunits', 's8_2_renttofmr',
       's8_2_inacstatusdesc', 'numberactivesection202',
       'numberinconclusivesection202', 'numberinactivesection202', 's202_1_id',
       's202_1_status', 's202_1_programname', 's202_1_startdate',
       's202_1_enddate', 's202_1_assistedunits', 's202_1_principalbalance',
       's202_1_inacstatusdesc', 's202_2_id', 's202_2_status',
       's202_2_programname', 's202_2_startdate', 's202_2_enddate',
       's202_2_assistedunits', 's202_2_principalbalance',
       's202_2_inacstatusdesc', 'numberactivesection236',
       'numberinconclusivesection236', 'numberinactivesection236', 's236_1_id',
       's236_1_status', 's236_1_programname', 's236_1_startdate',
       's236_1_enddate', 's236_1_assistedunits', 's236_1_inacstatusdesc',
       's236_2_id', 's236_2_status', 's236_2_programname', 's236_2_startdate',
       's236_2_enddate', 's236_2_assistedunits', 's236_2_inacstatusdesc',
       'numberactivehudinsured', 'numberinconclusivehudinsured',
       'numberinactivehud', 'fha_1_id', 'fha_1_status', 'fha_1_programname',
       'fha_1_startdate', 'fha_1_enddate', 'fha_1_assistedunits',
       'fha_1_principalbalance', 'fha_1_inacstatusdesc', 'fha_2_id',
       'fha_2_status', 'fha_2_programname', 'fha_2_startdate', 'fha_2_enddate',
       'fha_2_assistedunits', 'fha_2_principalbalance', 'fha_2_inacstatusdesc',
       'numberactivelihtc', 'numberinconclusivelihtc', 'numberinactivelihtc',
       'lihtc_1_id', 'lihtc_1_status', 'lihtc_1_programname',
       'lihtc_1_startdate', 'lihtc_1_enddate', 'lihtc_1_assistedunits',
       'lihtc_1_constructiontype', 'lihtc_1_inacstatusdesc', 'lihtc_2_id',
       'lihtc_2_status', 'lihtc_2_programname', 'lihtc_2_startdate',
       'lihtc_2_enddate', 'lihtc_2_assistedunits', 'lihtc_2_constructiontype',
       'lihtc_2_inacstatusdesc', 'numberactivesection515',
       'numberinconclusivesection515', 'numberinactivesection515',
       'rhs515_1_id', 'rhs515_1_status', 'rhs515_1_programname',
       'rhs515_1_startdate', 'rhs515_1_enddate', 'rhs515_1_assistedunits',
       'rhs515_1_principalbalance', 'rhs515_1_inacstatusdesc', 'rhs515_2_id',
       'rhs515_2_status', 'rhs515_2_programname', 'rhs515_2_startdate',
       'rhs515_2_enddate', 'rhs515_2_assistedunits',
       'rhs515_2_principalbalance', 'rhs515_2_inacstatusdesc',
       'numberactivesection538', 'numberinconclusivesection538',
       'numberinactivesection538', 'rhs538_1_id', 'rhs538_1_status',
       'rhs538_1_programname', 'rhs538_1_startdate', 'rhs538_1_enddate',
       'rhs538_1_assistedunits', 'rhs538_1_principalbalance',
       'rhs538_1_inacstatusdesc', 'rhs538_2_id', 'rhs538_2_status',
       'rhs538_2_programname', 'rhs538_2_startdate', 'rhs538_2_enddate',
       'rhs538_2_assistedunits', 'rhs538_2_principalbalance',
       'rhs538_2_inacstatusdesc', 'numberactivehome', 'numberinconclusivehome',
       'numberinactivehome', 'home_1_id', 'home_1_status',
       'home_1_programname', 'home_1_startdate', 'home_1_enddate',
       'home_1_assistedunits', 'home_1_constructiontype',
       'home_1_inacstatusdesc', 'home_2_id', 'home_2_status',
       'home_2_programname', 'home_2_startdate', 'home_2_enddate',
       'home_2_assistedunits', 'home_2_constructiontype',
       'home_2_inacstatusdesc', 'numberactivepublichousing',
       'numberinconclusivepublichousing', 'numberinactivepublichousing',
       'ph_1_id', 'ph_1_status', 'ph_1_programname', 'ph_1_startdate',
       'ph_1_enddate', 'ph_1_assistedunits', 'ph_1_inacstatusdesc',
       'ph_1_phacode', 'ph_2_id', 'ph_2_status', 'ph_2_programname',
       'ph_2_startdate', 'ph_2_enddate', 'ph_2_assistedunits',
       'ph_2_inacstatusdesc', 'ph_2_phacode', 'numberactivestate',
       'numberinconclusivestate', 'numberinactivestate', 'state_1_id',
       'state_1_status', 'state_1_programname', 'state_1_startdate',
       'state_1_enddate', 'state_1_assistedunits', 'state_1_inacstatusdesc',
       'state_1_constructiontype', 'state_2_id', 'state_2_status',
       'state_2_programname', 'state_2_startdate', 'state_2_enddate',
       'state_2_assistedunits', 'state_2_inacstatusdesc',
       'state_2_constructiontype', 'numberactivepbv', 'numberinconclusivepbv',
       'numberinactivepbv', 'pbv_1_status', 'pbv_1_programname',
       'pbv_1_assistedunits', 'pbv_2_status', 'pbv_2_programname',
       'pbv_2_assistedunits', 'numberactivemr', 'numberinconclusivemr',
       'numberinactivemr', 'mr_1_status', 'mr_1_programname',
       'mr_1_assistedunits', 'mr_2_status', 'mr_2_programname',
       'mr_2_assistedunits', 'oldnhpdpropertyid'],
      dtype='object')